---
name: release

on:
  push:
    branches:
    tags:

env:
  JOBS_NUM: "4"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v5
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker buildx create --use
      - run: make build
      - run: make release
      - uses: ncipollo/release-action@v1
        with:
          commit: main
          tag: v3.0.1
          artifacts: "solana-*.tar.bz2,sha256sum.txt"
          draft: true
          skipIfReleaseExists: true
