---
name: validate

on:
  push:
    branches:

env:
  JOBS_NUM: "4"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v5
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker buildx create --use
      - run: make build

      # Create a release when on main
      - run: make release
        if: github.ref == 'refs/heads/main'
      - name: Get version
        if: github.ref == 'refs/heads/main'
        id: get_version
        run: echo "version=$(make version)" >> $GITHUB_OUTPUT
      - uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          commit: main
          tag: ${{ steps.get_version.outputs.version }}
          artifacts: "solana-*.tar.bz2,sha256sum.txt"
          generateReleaseNotes: true
          skipIfReleaseExists: true
