---
name: release

on:
  push:
    branches:
    tags:

env:
  JOBS_NUM: "4"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker buildx create --use
      - run: make build
      - run: make release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
      - uses: ncipollo/release-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          artifacts: "build/agave-*.tar.xz,build/sha256sum.txt"
          draft: true
